services:
  - type: web
    name: sign-language-streamlit
    env: python
    region: oregon
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port 10000 --server.address 0.0.0.0
